version: "3"
services:
  app:
    image: ms-users
    container_name: ecoswap-container
    build: ./
    restart: always
    ports:
    - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
