version: "3"
services:
  app:
    image: ms-auth-manager
    container_name: javaserver2
    build: ./
    restart: always
    ports:
    - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080