version: "3"
services:

  no-ssl-nginx-front:
    image: nginx-front
    container_name: front-ecoswap
    build:
      context: front
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    networks:
      - default
 #   environment:
 #     - HOST=0.0.0.0
 #     - PORT=80

  no-ssl-ms-aunteticacion:
    image: ms-autenticacion
    container_name: ms-autenticacion-container
    build: 
      context: ms-autenticacion
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "8085:8085"
    environment:
      - HOST=0.0.0.0
      - PORT=8085
      
  no-ssl-ms-users:
    image: ms-users
    container_name: ms-user-container 
    build: 
      context: ms-users
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
